# Figure 1B ----------------------------------------------------------------

# This file includes code to reproduce Figure 1B in Ramirez et al. "Meta-analysis of primary producer amino acid δ15N values and their 
# influence on trophic position estimation." 

# Here we use simulation to illustrate how variation in β values and AA-specific TDFs propagate through a simple hypothetical food chain 
# to influence consumer trophic position estimates (TPCSIA). Within this simulation, Δ15NGlx declines from a mean of 8.0‰ to 6.1‰ to 4.4‰ 
# with each trophic step and has a SD of 1.2‰; Δ15NPhe has a mean ± SD of 0.4 ± 0.5‰ for all trophic transfers (McMahon & McCarthy 2016). 

# For each model run, the initial offset between δ15NGlx and δ15NPhe in primary producer (TPCSIA = 1) was defined by drawing random samples 
# from both the conventional β value (+3.4 ± 0.9‰) and simulated Phe (+0.4 ± 0.5‰) distributions, which were then used to estimate Glx (i.e., 
# estimated Glx = estimated Phe + estimated β). Glx and Phe estimates for the primary consumer (TPCSIA = 2) were then generated by drawing 
# random samples from the Δ15NGlx and Δ15NPhe distributions and adding them to the Glx and Phe estimates from the primary producer. This 
# process was then repeated for the secondary (TPCSIA = 3) and tertiary (TPCSIA = 4) consumers. 

# We ran the simulation 100 times, generating 100 hypothetical food chains. Once Glx and Phe estimates were generated for all model runs (i.e., 
# 4 taxa * 100 simulations = 400 paired Glx and Phe estimates), we used these data in conjunction with the McMahon & McCarthy (2016) multi-TDF 
# TPCSIA equation to estimate TPCSIA for each hypothetical consumer. For the TPCSIA calculation we used a β of +3.4‰ and TDFs (Δ15NGlx – Δ15NPhe) 
# of 7.6‰ (primary consumer), 5.7‰ (secondary consumer), and 4.4‰ (tertiary consumer). 

#### Load Packages

require(ggplot2)
require(tidyr)
require(dplyr)
require(tibble)
require(ggExtra)


#### Define Simulation Parameters

# Number of simulations (i.e., number of hypothetical food chain runs)
n.runs <- 100

# Ceate empty matrices to hold TP estimates for each consumers within hypothetical food chains
TP1 = matrix(NA, nrow = n.runs, ncol = 4) # primary producer (e.g., diatom)
TP2 = matrix(NA, nrow = n.runs, ncol = 4) # primary consumer (e.g., copepod)
TP3 = matrix(NA, nrow = n.runs, ncol = 4) # secondary consumer (e.g., fish)
TP4 = matrix(NA, nrow = n.runs, ncol = 4) # tetiary consumer (e.g., seal)

# Paramater mean values and SDs
beta.mean <- 3.4
beta.sd <- 0.9
phe.mean <- 0.4 
phe.sd <- 0.4
glu1.mean <- 8  # 1st trophic transfer
glu1.sd <- 1.2
glu2.mean <- 6.1  # 2nd trophic transfer
glu2.sd <- 1.2
glu3.mean <- 4.4  # 3rd trophic transfer
glu3.sd <- 1.2


#### Run Simulation

# For loop to simulate beta, phe, glue, and TP for consumers
# For each model run, TP successively estimated for each consumer from TP 1 to TP 4 using simulated TP estimates from the previous TP and 
# simulated glu and phe TDFs drawn from normal distributions with a mean of XX.mean and standard deviation of XX.sd.

for(i in 1:n.runs) {   #loop through consumers 
 
  # TP 1 - primary producer
  # For each simulated consumer, estimate a beta and phe then use these estimates to calculate glu
  beta.est1 <- rnorm(1, beta.mean, beta.sd)
  phe.est1 <- rnorm(1, 1, phe.sd)
  glu.est1 <- phe.est1 + beta.est1 
  
  # Record, beta, phe, glu in TP1 columns 1-3; use to estimate TP and record in TP1 column 4
  TP1[i,1] <- beta.est1
  TP1[i,2] <- phe.est1
  TP1[i,3] <- glu.est1
  TP1[i,4] <- 1 + ((glu.est1 - phe.est1) - beta.mean)/(glu1.mean-phe.mean)
  
  
  # TP 2 - primary consumer
  # For each simulated consumer, estimate a phe and glu TDF; add to mean phe and glu values from TP 1    
  phe.est2 <- mean(TP1[i,2]) + rnorm(1,phe.mean,phe.sd)
  glu.est2 <- mean(TP1[i,3]) + rnorm(1, glu1.mean, glu1.sd)
  
  # Record, phe, glu in TP2 columns 2-3; use to estimate TP and record in TP2 column 4
  TP2[i,1] <- TP1[i,1]  # store simulated beta
  TP2[i,2] <- phe.est2
  TP2[i,3] <- glu.est2
  TP2[i,4] <- 1 + ((glu.est2 - phe.est2) - beta.mean)/(glu1.mean-phe.mean)
  
  
  # TP 3 - secondary consumer
  # For each simulated consumer, estimate a phe and glu TDF; add to mean phe and glu values from TP 2    
  phe.est3 <- mean(TP2[i,2]) + rnorm(1,phe.mean,phe.sd)
  glu.est3 <- mean(TP2[i,3]) + rnorm(1, glu2.mean, glu2.sd)
  
  # Record, phe, glu in TP3 columns 2-3; use to estimate TP and record in TP3 column 4
  TP3[i,1] <- TP1[i,1]  # store simulated beta
  TP3[i,2] <- phe.est3
  TP3[i,3] <- glu.est3
  TP3[i,4] <- 2 + ((glu.est3 - phe.est3) - (glu1.mean-phe.mean) - beta.mean)/(glu2.mean-phe.mean)    #McMahon et al. 2016 -- TP3 TDF applied to all but first trophic transfer
  
  
  # TP 4 - tertiary consumer
  # For each simulated consumer, estimate a phe and glu TDF; add to mean phe and glu values from TP 3    
  phe.est4 <- mean(TP3[i,2]) + rnorm(1,phe.mean,phe.sd)
  glu.est4 <- mean(TP3[i,3]) + rnorm(1, glu3.mean, glu3.sd)

  # Record, phe, glu in TP4 columns 2-3; use to estimate TP and record in TP4 column 4
  TP4[i,1] <- TP1[i,1]  # store simulated beta
  TP4[i,2] <- phe.est4
  TP4[i,3] <- glu.est4
  TP4[i,4] <- 3 + ((glu.est4 - phe.est4) - (glu1.mean-phe.mean) - (glu2.mean-phe.mean) - beta.mean)/(glu3.mean-phe.mean)    #Modified from McMahone et al. 2016
}


#### Data Processing

# Convert matrices to data frames
TP1 <- as.data.frame(TP1)
TP2 <- as.data.frame(TP2)
TP3 <- as.data.frame(TP3)
TP4 <- as.data.frame(TP4)

# Combine all datasets; reorganize glu and phe estimates into one column
data <- do.call("rbind", list(TP1, TP2, TP3, TP4))
names(data)[1:4] <- c("beta.est", "phe.est","glu.est","tp.est")
data$tp.true <- c(rep(1,n.runs),rep(2,n.runs),rep(3,n.runs),rep(4,n.runs))

data2 <- gather(data, "phe.est","glu.est", key = "AA", value = "d15N")

data2$AA <- as.factor(data2$AA)
data2$tp.true <- as.factor(data2$tp.true)

data2$code <- paste(data2$tp.true,data2$AA)
data2$code <- as.factor(data2$code)

# Calculate group means; save as separate dataset
(group.means <- data2 %>% 
    group_by(tp.true,AA) %>%
    summarise(d15N.mean = mean(d15N), d15N.sd = sd(d15N),tp.mean = mean(tp.est), tp.sd = sd(tp.est)))

group.means <- as.data.frame(group.means)


### Plot data
# Note: We used Adobe Illustrator to re-color glu data and add data labels

# Figure 1B
(plot <- ggplot(data2, aes(tp.est, d15N, colour = code, shape =AA)) + geom_point(size=2) +
    theme_test() + theme(text=element_text(size=16)) + 
    scale_shape_manual(values=c(1,0)) + 
    scale_colour_manual(values=c("#bdbdbd","#009988", "#969696", "#0077bb",  "#737373","#ddaa33","#525252", "#cc3311")) +
    xlab("Trophic Position") + ylab(expression(paste(delta^{15},"N"," ","(\u2030)")))  +
    scale_x_continuous(limits=c(0.5, 5.5), breaks=seq(1,5,1)) + scale_y_continuous(limits=c(-1,28), breaks=seq(0,30,5)) +
    geom_point(data=group.means, aes(tp.mean,d15N.mean), colour="black", size=4, pch=c(16,15,16,15,16,15,16,15)) + 
    theme(legend.position = "none") )

# Add density plots to axes
ggMarginal(plot, type="density", groupColour = TRUE, groupFill = TRUE)

# Figure 1A
ggplot(group.means, aes(tp.mean, d15N.mean, shape = AA)) + geom_point(size=4) + #geom_line() +
  #geom_ribbon(aes(ymin = d15N.mean-1.85*d15N.sd, ymax = d15N.mean+1.85*d15N.sd), alpha=0.2) +
  theme_test() + theme(text=element_text(size=16)) + 
  scale_shape_manual(values=c(16,15), labels = c("Glu","Phe")) + 
  xlab("Trophic Level") + ylab(expression(paste(delta^{15},"N"," ","(\u2030)"))) +
  scale_x_continuous(limits=c(0.5, 5.5), breaks=seq(1,4,1)) + scale_y_continuous(limits=c(-1,27), breaks=seq(0,30,5)) +
  theme(legend.position = c(0.15, 0.85)) 



